### ISSUE TITLE
Doesn't work with Pygame v1

### ISSUE THREAD

**Issue by quantumjim** [pewpew-game/pew-pygame#3]
At least for me (OSX, Python 3.7.0) the emulator didn't work with the version of Pygame that pip provided. Instead I needed `pygame==2.0.0.dev1`. If this is a general issue, perhaps requirements.txt could specify this version.

**Comment by deshipu** [comment]
It should work with pretty much any version of PyGame. What was the error you got?

**Comment by quantumjim** [comment]
No error was reported. Just a blank and unresponsive screen.

It looks like a [problem with Mojave](https://github.com/pygame/pygame/issues/555). So maybe good to include a note in the README (I made a PR #4 for this, if you want it), or just keep it in mind during next week's workshops.

**Comment by deshipu** [comment]
Fixed by #4
