### ISSUE TITLE
Limited games support?

### ISSUE THREAD

**Issue by Eretick** [pewpew-game/pew-pygame#8]
Hi! Sorry, thats not completely an error, but idk where I could ask it.
I tried use Pewmulator, but a lot of games using ugame and stage library. 
And some of them using digitalio, board and same libraries. So then I try to launch this game on PC, i expectedly getiing "no module named ..." error.
Where I can find this kind of modules to make python think he runs on hardware?

**Comment by deshipu** [comment]
This is just for the Pew library, I don't currently have emulation for the Stage library or DisplayIO. You may take a look at Blinka (https://github.com/adafruit/Adafruit_Blinka) that provides a layer of emulation that lets you use most CircuitPython libraries with regular Python — but I'm not sure if it currently supports DisplayIO or regular PC computers without any extra hardware.
